const_value = 1

	const BULBASAUR 	 
	const IVYSAUR 	 
	const VENUSAUR 	 
	const CHARMANDER 	 
	const CHARMELEON 	 
	const CHARIZARD 	 
	const SQUIRTLE 	 
	const WARTORTLE 	 
	const BLASTOISE 	 
	const CATERPIE 	 
	const METAPOD 	 
	const BUTTERFREE 	 
	const WEEDLE 		 
	const KAKUNA 		 
	const BEEDRILL 	 
	const PIDGEY 		 
	const PIDGEOTTO 	 
	const PIDGEOT 	 
	const RATTATA 	 
	const RATICATE 	 
	const SPEAROW 	 
	const FEAROW 		 
	const EKANS 		 
	const ARBOK 		 
	const PIKACHU 	 
	const RAICHU 		 
	const SANDSHREW 	 
	const SANDSLASH 	 
	const NIDORAN_F 	 
	const NIDORINA 	 
	const NIDOQUEEN 	 
	const NIDORAN_M 	 
	const NIDORINO 	 
	const NIDOKING 	 
	const CLEFAIRY 	 
	const CLEFABLE 	 
	const VULPIX 		 
	const NINETALES 	 
	const JIGGLYPUFF 	 
	const WIGGLYTUFF 	 
	const ZUBAT 		 
	const GOLBAT 		 
	const ODDISH 		 
	const GLOOM 		 
	const VILEPLUME 	 
	const PARAS 		 
	const PARASECT 	 
	const VENONAT 	 
	const VENOMOTH 	 
	const DIGLETT 	 
	const DUGTRIO 	 
	const MEOWTH 		 
	const PERSIAN 	 
	const PSYDUCK 	 
	const GOLDUCK 	 
	const MANKEY 		 
	const PRIMEAPE 	 
	const GROWLITHE 	 
	const ARCANINE 	 
	const POLIWAG 	 
	const POLIWHIRL 	 
	const POLIWRATH 	 
	const ABRA 		 
	const KADABRA 	 
	const ALAKAZAM 	 
	const MACHOP 		 
	const MACHOKE 	 
	const MACHAMP 	 
	const BELLSPROUT 	 
	const WEEPINBELL 	 
	const VICTREEBEL 	 
	const TENTACOOL 	 
	const TENTACRUEL 	 
	const GEODUDE 	 
	const GRAVELER 	 
	const GOLEM 		 
	const PONYTA 		 
	const RAPIDASH 	 
	const SLOWPOKE 	 
	const SLOWBRO 	 
	const MAGNEMITE 	 
	const MAGNETON 	 
	const FARFETCHD 	 
	const DODUO 		 
	const DODRIO 		 
	const SEEL 		 
	const DEWGONG 	 
	const GRIMER 		 
	const MUK 		 
	const SHELLDER 	 
	const CLOYSTER 	 
	const GASTLY 		 
	const HAUNTER 	 
	const GENGAR 		 
	const ONIX 		 
	const DROWZEE 	 
	const HYPNO 		 
	const KRABBY 		 
	const KINGLER 	 
	const VOLTORB 	 
	const ELECTRODE 	 
	const EXEGGCUTE 	 
	const EXEGGUTOR 	 
	const CUBONE 		 
	const MAROWAK 	 
	const HITMONLEE 	 
	const HITMONCHAN 	 
	const LICKITUNG 	 
	const KOFFING 	 
	const WEEZING 	 
	const RHYHORN 	 
	const RHYDON 		 
	const CHANSEY 	 
	const TANGELA 	 
	const KANGASKHAN 	 
	const HORSEA 		 
	const SEADRA 		 
	const GOLDEEN 	 
	const SEAKING 	 
	const STARYU 		 
	const STARMIE 	 
	const MR_MIME 	 
	const SCYTHER 	 
	const JYNX	     
	const ELECTABUZZ 	 
	const MAGMAR 		 
	const PINSIR 		 
	const TAUROS 		 
	const MAGIKARP 	 
	const GYARADOS 	 
	const LAPRAS 		 
	const DITTO 		 
	const EEVEE 		 
	const VAPOREON 	 
	const JOLTEON 	 
	const FLAREON 	 
	const PORYGON 	 
	const OMANYTE 	 
	const OMASTAR 	 
	const KABUTO 		 
	const KABUTOPS 	 
	const AERODACTYL 	 
	const SNORLAX 	 
	const ARTICUNO 	 
	const ZAPDOS 		 
	const MOLTRES 	 
	const DRATINI 	 
	const DRAGONAIR 	 
	const DRAGONITE 	 
	const MEWTWO 		 
	const MEW 		 
	const NOSEPASS	 
	const PROBOPASS	 
	const MIMIKYU	     
	const TOGEPI	     
	const TOGETIC	     
	const YAMASK       
	const COFAGRIGUS	 
	const FOMANTIS     
	const LURANTIS	
	const ROWLET       
	const DARTRIX      
	const DECIDUEYE    
	const LITWICK	 
	const LAMPENT 	 
	const CHANDELURE 	 
	const MUDKIP 	     
	const MARSHTOMP 	 
	const SWAMPERT  	 
	const SWABLU       
	const ALTARIA      
	const GRUBBIN      
	const CHARJABUG    
	const VIKAVOLT     
	const SNEASEL      
	const SMEARGLE     
	const MICOMON    
	const CROBAT       
	const SCIZOR       
	const TRAPINCH     
	const VIBRAVA      
	const FLYGON       
	const SANDILE    
	const KROKOROK
	const KROOKODILE
	const SOLOSIS      
	const DUOSION      
	const REUNICLUS    
	const CATERMANO        
	const LUCARIO      
	const TIMBURR
	const GURDURR 
	const CONKELDURR        
	const TYRANITAR      
	const STEELIX
	const BELDUM     
	const METANG      
	const METAGROSS
	const DARK_PIKA
	const ZOROARK
	const DRAMPA     
	const WEAVILE
	const DRILLBUR
	const EXCADRILL
	const TYNAMO
	const EELEKTRIK
	const EELEKTROSS
	const SNOVER
	const ABOMASNOW
	const TOGEKISS
	const HERACROSS
	const ESPEON
	const UMBREON	
	const LEAFEON
	const GLACEON
	const HOUNDOUR
	const HOUNDOOM
	const CHINCHOU
	const LANTURN	
	const MURKROW
	const HONCHKROW
	const HYDREIGON
	const CARVANHA
	const SHARPEDO
	const NUMEL
	const CAMERUPT
	const RHYPERIOR
	const KINGDRA
	const SKARMORY
	const SALAMENCE
	const MAGNEZONE
	const TANGROWTH
	const ELECTIVIRE
	const MAGMORTAR
	const LICKILICKY
	const PORYGON2
	const PORYGONZ

	const FOSSIL_KABUTOPS 	 
	const FOSSIL_AERODACTYL 	 
	const MON_GHOST 			 